site_name: Last Descent
repo_url: https://github.com/ehrpg/lastdescent
site_author: "@nola"

theme: readthedocs

pages:
  - Introduction: 'index.md'
  - Overview: 'overview.md'
  - Technology: 'technology.md'
  - 'Character Options':
    - Races: 'races.md'
    - Perks: 'perks.md'
    - Flaws: 'flaws.md'
    - Equipment: 'equipment.md'
  - Space:
      - Space Flight: 'space/flight.md'
      - Stations: 'space/stations.md'
      - Treaty of 2038: 'space/laws.md'
  - Earth:
      - Nations: 'places/earth/nations.md'
      - Vessels: 'places/earth/vessels.md'
  - Mars:
      - History: 'places/mars/history.md'
      - Planet: 'places/mars/planet.md'
      - First Martian Republic: 'places/mars/fmr.md'
      - Vessels: 'places/mars/vessels.md'
  - Kepler:
      - Planet: 'places/kepler/planet.md'
      - History: 'places/kepler/history.md'
      - Colony: 'places/kepler/colony.md'
  - Stations:
      - Ceres: 'places/stations/ceres.md'
      - Rhea: 'places/stations/rhea.md'
      - Venus: 'places/stations/venus.md'
      - Ganymede: 'places/stations/ganymede.md'
      - Pluto: 'places/stations/pluto.md'
      - Opus: 'places/stations/opus.md'
      - Osiris: 'places/mars/osiris.md'
  - Factions:
      - Dark Dawn: 'factions/darkdawn.md'
      - IPA:
          - Overview: 'factions/ipa/overview.md'
          - Vessels: 'factions/ipa/vessels.md'
      - Fenrir:
          - Overview: 'factions/fenrir/overview.md'
          - Vessels: 'factions/fenrir/vessels.md'
      - Organised Crime: 'factions/crime.md'
      - Syndicate: 'factions/syndicate.md'
      - SART: 'factions/sart.md'
      - F.O.S.: 'factions/fos.md'
