site_name: Last Descent
repo_url: https://github.com/n0la/lastdescent
site_author: "@nola"

theme: readthedocs

pages:
  - Introduction: 'index.md'
  - Overview: 'overview.md'
  - Races: 'races.md'
  - Space:
      - Space Flight: 'space/flight.md'
      - Stations: 'space/stations.md'
  - Earth:
      - Nations: 'places/earth/nations.md'
  - Mars:
      - History: 'places/mars/history.md'
      - Planet: 'places/mars/planet.md'
      - First Martian Republic: 'places/mars/fmr.md'
  - Kepler: 'places/kepler.md'
