site_name: Last Descent
repo_url: https://github.com/n0la/lastdescent
site_author: "@nola"

theme: readthedocs

pages:
  - Introduction: 'index.md'
  - Overview: 'overview.md'
  - 'Character Options':
    - Races: 'races.md'
    - Perks: 'perks.md'
    - Flaws: 'flaws.md'
  - Space:
      - Space Flight: 'space/flight.md'
      - Stations: 'space/stations.md'
      - Treaty of 2038: 'space/laws.md'
  - Earth:
      - Nations: 'places/earth/nations.md'
      - Vessels: 'places/earth/vessels.md'
  - Mars:
      - History: 'places/mars/history.md'
      - Planet: 'places/mars/planet.md'
      - First Martian Republic: 'places/mars/fmr.md'
      - Vessels: 'places/mars/vessels.md'
  - Kepler:
      - Planet: 'places/kepler/planet.md'
      - History: 'places/kepler/history.md'
      - Colony: 'places/kepler/colony.md'
  - Stations:
      - Ceres: 'places/stations/ceres.md'
      - Rhea: 'places/stations/rhea.md'
  - Factions:
      - Black Dawn: 'factions/darkdawn.md'
      - IPA: 'factions/ipa.md'
